# Generated by Django 2.1.1 on 2018-10-05 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content_front', models.TextField()),
                ('content_back', models.TextField()),
                ('created', models.DateTimeField()),
                ('changed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FlashCardStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('changed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('changed', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='flashcardstack',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.User'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='cardstack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.FlashCardStack'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.User'),
        ),
    ]
